server:
  port: 8080

spring:
  application:
    name: pedidos360
  rabbitmq:
    host: localhost
    port: 5672
    username: labuser
    password: labpass
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
